Fix missing dsra schema error
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) schema "dsra" does not exist
https://github.com/anthonyfok/opendrr-api/runs/2857777725?check_suite_focus=true